# Generated by Django 4.2 on 2023-12-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='product',
        ),
    ]
