# Generated by Django 4.2 on 2023-12-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_remove_link_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='create',
            field=models.DateTimeField(auto_now=True, verbose_name='время создания'),
        ),
        migrations.AddField(
            model_name='link',
            name='debt',
            field=models.FloatField(default=0, verbose_name='долг'),
        ),
        migrations.AddField(
            model_name='link',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.link', verbose_name='поставщик'),
        ),
    ]
