# Generated by Django 4.2 on 2023-12-25 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0003_link_create_link_debt_link_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'звено', 'verbose_name_plural': 'звенья'},
        ),
        migrations.AddField(
            model_name='link',
            name='factory',
            field=models.BooleanField(default=False, verbose_name='завод'),
        ),
        migrations.AddField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='link',
            name='debt',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='долг'),
        ),
    ]
