# Generated by Django 4.2 on 2023-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_link_options_link_factory_link_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='factory',
        ),
        migrations.AddField(
            model_name='link',
            name='structure',
            field=models.CharField(choices=[('FC', 'factory'), ('RN', 'retail network'), ('IE', 'individual entrepreneur')], default=None, max_length=2, verbose_name='структура'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='debt',
            field=models.FloatField(default=0, verbose_name='долг'),
        ),
    ]
