# Generated by Django 4.2 on 2023-12-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_remove_link_factory_link_structure_alter_link_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
